=== Andrespolijic65/Ejercicio5/ejercicio5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT listacursos (cursos)+>
<!ELEMENT cursos (alumnos)+>
        <!ELEMENT alumnos (dni, nombre, apellido1, apellido2?, listaasignaturas)>
<!ELEMENT listaasignaturas (asignatura+)>
<!ELEMENT asignatura (nombre,profesor)>
<!ATTLIST asignatura codigo CDATA #REQUIRED>
<!ELEMENT profesor (nrp,nombre,apellido1,apellido2?)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>
<!ELEMENT nrp (#PCDATA)>

=== Andrespolijic65/Ejercicio5/ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacursos SYSTEM "ejercicio5.dtd">
<listacursos>
    <cursos>
        <alumnos>
            <dni> 1245678 </dni>
            <nombre>Andres</nombre>
            <apellido1>Gonzales </apellido1>
            <apellido2>Molina</apellido2>
            <listaasignaturas>
               <asignatura codigo="AS1">
                   <nombre>Base de datos 2</nombre>
                  <profesor>
                      <nrp> 34567 </nrp>
                      <nombre>Felipe </nombre>
                      <apellido1>Rodriguez </apellido1>
                  </profesor>
               </asignatura>
            </listaasignaturas>
        </alumnos>
    </cursos>
</listacursos>
